app = 's-ashwath-squall'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  FLASK_HOST = '127.0.0.1'
  FLASK_PORT = '5001'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
